ALTER TABLE livros ADD COLUMN IF NOT EXISTS editora VARCHAR(150);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS ano_publicacao SMALLINT CHECK (ano_publicacao IS NULL OR ano_publicacao BETWEEN 1400 AND 2100);
