ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS cor_menu   VARCHAR(7) NOT NULL DEFAULT '#1e1b4b';
ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS cor_login  VARCHAR(7) NOT NULL DEFAULT '#4f46e5';
ALTER TABLE configuracoes ADD COLUMN IF NOT EXISTS cor_botoes VARCHAR(7) NOT NULL DEFAULT '#4f46e5';
